Add Question results summary page
Som-Energia/decidim-som-energia-app pull request #64
Opened 2021-03-21 20:14 UTC by aitorlb

Related issue: #57

2021-03-21 20:15 UTC, aitorlb commented
Needs to be rebased after #62 is merged

2021-03-22 17:16 UTC, microstudi commented
@aitorlb ready to rebase!

2021-03-23 09:17 UTC, microstudi commented
Sorry @aitorlb this needs rebase again, cos' I've merged #63

2021-03-24 12:10 UTC, microstudi requested changes
Thanks @aitorlb this looks and behaves nice!

However we will need to work a little further in it:
- currently only the questions can be viewed in a summary mode.
- We should be able to do the same for a specific consultation so we can see all the questions and navigate the summary of the question when clicked.

Something like:
http://localhost:3000/consultations/laboriosam-voluptatem/summary
behaving similar as the question summary view, and when clicking on the question "view results" button direct the user to the question summary view.

We also going to need a "return to consultation" button on the top of the question summary.

With this we will be good to go.

2021-04-06 11:31 UTC, microstudi requested changes
I've been testing this, it is ok, 3 things:
- [ ] some old customizations collide with the new views (method `previous_published_questions` do not exist). This is due `NeedsQuestion` is overriden.
- [ ] `/summary` path must be done via Rails routes to take into account locales
- [ ] Readme needs a description of the feature

Note: I'll commit the fixes myself due the timing! Thanks for the work @aitorlb !

2021-04-06 11:31 UTC, microstudi commented on app/views/decidim/consultations/consultation_summaries/_question.html.erb
> +            <%= link_to "#{question_path(question)}/summary",
This should be done by using Rails routes to take into account query variables (ie: locale)
```suggestion
      <%= link_to "#{Rails.application.routes.url_helpers.question_summary_path(question, locale: params[:locale])}",
```

2021-04-06 12:27 UTC, merged